// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4HfeSaEQKhT__xu2VtQ_26BzamfGPbl8',
    appId: '1:1045831640194:web:da5a26dc8f693b855ac09b',
    messagingSenderId: '1045831640194',
    projectId: 'aliment-app',
    authDomain: 'aliment-app.firebaseapp.com',
    storageBucket: 'aliment-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQQynV12tqni2071gzpWqu56KLK023H8',
    appId: '1:1045831640194:android:05b47a3886c1e3575ac09b',
    messagingSenderId: '1045831640194',
    projectId: 'aliment-app',
    storageBucket: 'aliment-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qFSrynR11XrLA4EmhKNz2CwHEpe8SxA',
    appId: '1:1045831640194:ios:120c80cb5679481d5ac09b',
    messagingSenderId: '1045831640194',
    projectId: 'aliment-app',
    storageBucket: 'aliment-app.firebasestorage.app',
    iosBundleId: 'com.example.aliment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7qFSrynR11XrLA4EmhKNz2CwHEpe8SxA',
    appId: '1:1045831640194:ios:120c80cb5679481d5ac09b',
    messagingSenderId: '1045831640194',
    projectId: 'aliment-app',
    storageBucket: 'aliment-app.firebasestorage.app',
    iosBundleId: 'com.example.aliment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4HfeSaEQKhT__xu2VtQ_26BzamfGPbl8',
    appId: '1:1045831640194:web:5ad92d7fe4bfb6925ac09b',
    messagingSenderId: '1045831640194',
    projectId: 'aliment-app',
    authDomain: 'aliment-app.firebaseapp.com',
    storageBucket: 'aliment-app.firebasestorage.app',
  );
}
